# Generated by Django 2.0 on 2019-11-20 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name of Event')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='Description')),
                ('max_slots', models.IntegerField(blank=True, null=True, verbose_name='Max Slots')),
                ('date_from', models.DateField(verbose_name='Start Date')),
                ('date_to', models.DateField(verbose_name='End Date')),
                ('time_from', models.TimeField(verbose_name='Start Time')),
                ('time_to', models.TimeField(verbose_name='End Time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
